export const lang = {
    fr: {
        LOADING: 'Chargement...',
        LANGUAGE: 'Language',
        VALID: 'Valider',
        PLAY_RANDOM: 'Partie aléatoire',
        CREATE_JOIN: 'Créer/rejoindre une partie',
        JOIN: 'Rejoindre',
        CREATE: 'Créer',
        OR: 'Ou',
        RETURN: 'Retour',
        FIND: 'Saisez le nom de la partie',
        NO_CONNECTION: 'Network issues',
        PLAY: 'Rejoindre une partie',
        WAITING_MENU: 'Attente d\'une partie...',
        WAITING_READY: 'L\'adversaire n\'est pas encore prêt\nVeuillez patienter...',
        WIN: 'Vous avez GAGNÉ !',
        LOOSE: 'Vous avez perdu...',
        READY: 'Prêt',
        CONNECTION: 'Créer un compte/Se connecter',
        LOGGED: 'Accès authorisé',
        LOG_OR_PASS: 'Saisissez un mot de passe et une adresse Email',
        EMAIL_ALLREADY_EXIST: 'L\'Email existe déjà',
        PSEUDO_ALLREADY_EXIST: 'le pseudonyme existe déjà',
        DONT_MATCH: 'L\'Email et le mot de passe ne correspondent pas',
        HI: 'Bienvenue ',
        RATIO: 'Votre ratio est de ',
        SURE: 'Êtes vous sure ?',
        YES: 'Oui',
        NO: 'Non'
    },

    en: {
        LOADING: 'Loading...',
        LANGUAGE: 'Langue',
        VALID: 'Submit',
        PLAY_RANDOM: 'Play random',
        CREATE_JOIN: 'Create/join a game',
        JOIN: 'Join',
        CREATE: 'Create',
        OR: 'Or',
        RETURN: 'Return',
        NO_CONNECTION: 'no connection',
        PLAY: 'Play',
        WAITING_MENU: 'Waiting for a game...',
        WAITING_READY: 'Waiting for the other dude\nto be ready...',
        WIN: 'You WIN !',
        LOOSE: 'You loose...',
        READY: 'Ready',
        CONNECTION: 'Sign up/in',
        LOGGED: 'Acces granted',
        LOG_OR_PASS: 'You must send the email and the password',
        EMAIL_ALLREADY_EXIST: 'Email already Taken',
        PSEUDO_ALLREADY_EXIST: 'Pseudonym already taken',
        DONT_MATCH: 'The email or password don\'t match',
        HI: 'Welcome ',
        RATIO: 'Your ratio is ',
        SURE: 'Are you sure ?',
        YES: 'Yes',
        NO: 'No'
    },

    es: {
        LOADING: 'Cargando...',
        LANGUAGE: 'Idioma',
        VALID: 'Validar',
        PLAY_RANDOM: 'Parte aleatoria',
        CREATE_JOIN: 'Crear/unirse un juego',
        JOIN: 'Unirse',
        CREATE: 'Crear',
        OR: 'O',
        RETURN: 'Espalda',
        NO_CONNECTION: 'No hay conexión',
        PLAY: 'Jugar',
        WAITING_MENU: 'Esperando un juego...',
        WAITING_READY: 'Esperando que el otro amigo esté listo...',
        WIN: 'habéis ganado !',
        LOOSE: 'habéis perdido...',
        READY: 'Listo',
        CONNECTION: 'Regístrate/Registrarse',
        LOGGED: 'Acceso concedido',
        LOG_OR_PASS: 'Debe enviar el correo electrónico y la contraseña',
        EMAIL_ALLREADY_EXIST: 'Correo electrónico ya tomado',
        PSEUDO_ALLREADY_EXIST: 'Seudónimo ya tomado',
        DONT_MATCH: 'El correo electrónico o la contraseña no coinciden',
        HI: 'Bienvenido ',
        RATIO: 'Su ratio es ',
        SURE: 'Seguro ?',
        YES: 'Si',
        NO: 'No'
    }
};

